spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YangZhengXing0/springcloud-Config-sell-test.git
  rabbitmq:
    host: 192.168.99.100
    port: 5672
#          basedir: /Users/admin/code/myProjects/java/imooc/SpringCloud_Sell/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://weifuwukt.com:9000/eureka
management:
  endpoints:
    web:
      expose: "*"